### ISSUE TITLE
Structures are not generated correctly

### ISSUE THREAD

**Issue by CoolChicken321** [AkashiiKun/CavesCliffsPartTwoMod#5]
No structures (villages, monuments, pillager outpost, etc.) are spawned when there is a cave biome below. Something similar happens with Mineshaft and Strongholds, they do not generate spawners with caves spiders or silverfish.

**Comment by legosteenjaap** [comment]
the first issue is fixed i will look into spawners not generating

**Comment by AkashiiKun** [comment]
Fixed too.

**Comment by AkashiiKun** [comment]
https://github.com/AkashiiKun/CavesCliffsPartTwoMod/blob/f3232279ef1569da976031737e6feaa02f735a19/src/main/java/io/github/akashiikun/ccgen/mixin/MixinDefaultBiomeFeatures.java#L176

https://github.com/AkashiiKun/CavesCliffsPartTwoMod/blob/f3232279ef1569da976031737e6feaa02f735a19/src/main/java/io/github/akashiikun/ccgen/mixin/MixinDefaultBiomeFeatures.java#L196

**Comment by AkashiiKun** [comment]
Also added strongholds and mineshafts.

**Comment by legosteenjaap** [comment]
This issue is not yet fixed, there are still no spawners in strongholds, mineshafts and nether fortresses.

**Comment by legosteenjaap** [comment]
bug is not present when disabling mixinchunkgenerator

**Comment by AkashiiKun** [comment]
Then how can we fix it?

**Comment by legosteenjaap** [comment]
i found a way to fix it for the stronghold, but i want to try to find a way to do it for all structures with one mixin instead of one mixin for each structure.

**Comment by legosteenjaap** [comment]
Maybe it is faster if i do it per feature and if other mods also don't generate spawners i will maybe look further into this issue.
